# Introduction {#introduction}

In [1]:
#ex-class

# Run this cell first to download and import the required dependencies (it may take a while)
%pip install gensim

from openai import OpenAI
import pandas as pd
from urllib import request
from IPython.display import display, HTML
import spacy

try:
    spacy.load("en_core_web_sm")
except OSError:  # e.g. Google Colab
    spacy.cli.download("en_core_web_sm")
import gensim.downloader as api

wv50 = api.load("glove-wiki-gigaword-50")  # 50-dimensional
wv100 = api.load("glove-wiki-gigaword-100")  # 100-dimensional

Note: you may need to restart the kernel to use updated packages.


## Why Text Analytics?

In [2]:
# #ex-class

# # https://platform.openai.com/settings/organization/api-keys
# # https://firebasestorage.googleapis.com/v0/b/uni-sofia.appspot.com/o/lit%2Fopen_ai_key.txt?alt=media&token=23ae3ea6-013f-490d-a04b-b49c762a94b9

# client = OpenAI(
#     # This is the default and can be omitted
#     api_key="",
# )


# # https://platform.openai.com/docs/models

# response = client.responses.create(
#     model="gpt-4.1-nano",
#     # System message
#     instructions=" ".join(["You are a really nasty coding assistant.", "You try to be as unpolite as you can."]),
#     # User message
#     input="How do I write a for loop in Python?",
# )

# print(response.output_text)

## Language

:::{.ex-class}
![https://imgs.xkcd.com/1576](https://imgs.xkcd.com/comics/i_could_care_less.png)
:::

## The Early Approaches

:::{.ex-class}
- Rules-based systems, e.g. [ELIZA](https://www.masswerk.at/elizabot/) (1966)
- Lexicon approaches for classification and sentiment analysis
- Bag-of-word approaches (e.g. [TF-IDF](https://en.wikipedia.org/wiki/Tf%E2%80%93idf))
:::

## Modern Approaches

:::{.ex-class}
![Word2vec](https://miro.medium.com/v2/resize:fit:640/format:webp/1*7IbyPPIwaCUnyWg0T-4w1A.png)
:::

:::{.ex-class}
![Attention is all you need](https://indieresearch.net/wp-content/uploads/2024/02/image-4.png)
:::

In [3]:
#ex-class

url_handle = request.urlopen("https://raw.githubusercontent.com/boyko/text-analytics-script/main/data/ballet.txt")
article = url_handle.read().decode("utf-8")

display(HTML(f"<pre style='white-space: pre-wrap; word-wrap: break-word;'>{article[:1000]}</pre>"))

In [4]:
#ex-class

# What we will do is apply a simple splitting based on periods.

"A great ballet performance. Everybody liked it!".split(".")

['A great ballet performance', ' Everybody liked it!']

In [5]:
article_sents = article.split(".")

print(f"The articles contain {len(article_sents)} sentences(counting periods as sentence boundaries).\n\n")
print(f"The first 8 sentences are\n")

for i, sent in enumerate(article_sents[:8], start=1):
    print(f"{i}: {sent.strip()[:100]}")

The articles contain 167 sentences(counting periods as sentence boundaries).


The first 8 sentences are

1: With apologies to James Brown, the hardest working people in show business may well be ballet dancer
2: And at New York City Ballet, none work harder than the dancers in its lowest rank, the corps de ball
3: During the first week of the company’s winter season, Claire Kretzschmar, 24, a rising corps member,
4: But her work onstage did not even begin to capture the stamina required to be in the corps
5: Spending a week shadowing Ms
6: Kretzschmar was exhausting — she gave new meaning to the idea of being on your feet all day
7: Twelve-hour days at the David H
8: Koch Theater, the company’s Lincoln Center home, were hardly unusual: Company class each morning was


In [6]:
nlp = spacy.load("en_core_web_sm")

doc = nlp(article)

for i, sent in enumerate(list(doc.sents)[:8], start=1):
    print(f"{i}: {sent.text.strip()}")

OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

In [ ]:
MALE_WORDS = set([
    'guy', 'spokesman', 'chairman', "men's", 'men', 'him', "he's", 'his',
    'boy', 'boyfriend', 'boyfriends', 'boys', 'brother', 'brothers', 'dad',
    'dads', 'dude', 'father', 'fathers', 'fiance', 'gentleman', 'gentlemen',
    'god', 'grandfather', 'grandpa', 'grandson', 'groom', 'he', 'himself',
    'husband', 'husbands', 'king', 'male', 'man', 'mr', 'nephew', 'nephews',
    'priest', 'prince', 'son', 'sons', 'uncle', 'uncles', 'waiter', 'widower',
    'widowers'
])

FEMALE_WORDS = set([
    'heroine', 'spokeswoman', 'chairwoman', "women's", 'actress', 'women',
    "she's", 'her', 'aunt', 'aunts', 'bride', 'daughter', 'daughters', 'female',
    'fiancee', 'girl', 'girlfriend', 'girlfriends', 'girls', 'goddess',
    'granddaughter', 'grandma', 'grandmother', 'herself', 'ladies', 'lady',
    'mom', 'moms', 'mother', 'mothers', 'mrs', 'ms', 'niece', 'nieces',
    'priestess', 'princess', 'queens', 'she', 'sister', 'sisters', 'waitress',
    'widow', 'widows', 'wife', 'wives', 'woman'
])

Category: unknown
Sentence: With apologies to James Brown, the hardest working people in show business may well be ballet dancers

Category: unknown
Sentence:  And at New York City Ballet, none work harder than the dancers in its lowest rank, the corps de ballet

Category: unknown
Sentence:  During the first week of the company’s winter season, Claire Kretzschmar, 24, a rising corps member, danced in all seven performances, appearing in five ballets, sometimes changing costumes at intermission to dance two roles in a night

Category: female
Sentence: 

But her work onstage did not even begin to capture the stamina required to be in the corps

Category: unknown
Sentence:  Spending a week shadowing Ms

Category: female
Sentence:  Kretzschmar was exhausting — she gave new meaning to the idea of being on your feet all day

Category: unknown
Sentence:  Twelve-hour days at the David H

Category: unknown
Sentence:  Koch Theater, the company’s Lincoln Center home, were hardly unusual: Company 

## A More Flexible Approach

In [ ]:
pos_texts = [
    "we love you",
    "they love us",
    "you are good",
    "he is good",
    "they love mary"
]

neg_texts = [
    "we hate you",
    "they hate us",
    "you are bad",
    "he is bad",
    "we hate mary"
]

test_texts = [
    "they love mary",
    "they are good",
    "why do you hate mary",
    "they are almost always good",
    "we are very bad"
]

dt = pd.DataFrame({
    "text": pos_texts + neg_texts,
    "sentiment": ["positive"] * len(pos_texts) + ["negative"] * len(neg_texts)
})

dt

,text,sentiment
0,we love you,positive
1,they love us,positive
2,you are good,positive
3,he is good,positive
4,they love mary,positive
5,we hate you,negative
6,they hate us,negative
7,you are bad,negative
8,he is bad,negative
9,we hate mary,negative


In [ ]:
# First, it is convenient to create a function that will return a dictionary of words

def build_words2idx(text):
    words2idx = {}
    
    counter = 0
    
    for word in text.split(' '):
        if word not in words2idx:
            words2idx[word] = counter
            counter += 1
    return words2idx

words2idx = build_words2idx(dt["text"].str.cat(sep=' '))
print(words2idx)

vocabulary = list(words2idx.keys())
print(vocabulary)


{'we': 0, 'love': 1, 'you': 2, 'they': 3, 'us': 4, 'are': 5, 'good': 6, 'he': 7, 'is': 8, 'mary': 9, 'hate': 10, 'bad': 11}
['we', 'love', 'you', 'they', 'us', 'are', 'good', 'he', 'is', 'mary', 'hate', 'bad']


## Numerical Representations of Text

In [ ]:
import numpy as np
from plotly.subplots import make_subplots

import plotly.graph_objects as go

# Words given
words = ["dog", "cat", "plane", "air"]

e_dog = np.array([0.1, 0.2, 0.3])
e_cat = np.array([0.15, 0.25, 0.35])
e_plane = np.array([0.7, 0.8, 0.9])
e_air = np.array([0.4, 0.5, 0.8])

embeddings = np.array([e_dog, e_cat, e_plane, e_air])
fig = make_subplots(rows=1, cols=1, specs=[[{'type': 'scatter3d'}]])
fig.add_trace(
    go.Scatter3d(
        x=embeddings[:, 0],
        y=embeddings[:, 1],
        z=embeddings[:, 2],
        mode='markers+text',
        text=words,
        textposition='top center',
        marker=dict(
            size=8,
            color='blue',
            opacity=0.8
        )
    ),
    row=1, col=1
)

fig.update_layout(
    title="3D Word Embeddings: a dog, a cat, and a plane in the air",
    scene=dict(
        xaxis_title='Dimension 1',
        yaxis_title='Dimension 2',
        zaxis_title='Dimension 3',
        xaxis=dict(nticks=10, range=[-1, 1]),
        yaxis=dict(nticks=10, range=[-1, 1]),
    )
)

fig.show()

In [ ]:
wv50["boyko"]

array([-0.63864  ,  0.55225  , -0.02868  ,  1.4372   ,  0.84621  ,
        0.086462 ,  1.0269   , -0.15749  , -1.7303   ,  0.78138  ,
        0.97081  ,  0.28231  ,  0.80014  ,  0.30619  ,  0.51364  ,
        0.71541  ,  0.13712  ,  0.15678  ,  0.070215 ,  0.73268  ,
        0.43494  , -0.69873  , -0.48352  , -0.0078218,  0.092079 ,
        0.24763  ,  1.3196   ,  0.20335  , -0.56744  ,  0.087805 ,
       -1.2117   ,  0.77176  ,  0.51919  , -0.45287  , -0.542    ,
        0.44883  ,  0.71517  ,  0.068222 , -0.25429  ,  0.44027  ,
        0.46519  ,  1.036    , -0.80562  , -0.56505  ,  0.38988  ,
       -0.55556  , -0.92507  ,  0.1579   ,  1.5758   , -0.38589  ],
      dtype=float32)

In [ ]:
from sklearn.decomposition import PCA

# Get the 100-dimensional embeddings for the words from wv100
words_to_plot = ["dog", "cat", "plane", "air"]
embeddings_100d = np.array([wv100[word] for word in words_to_plot])

# Use PCA to reduce from 100 dimensions to 3 dimensions for visualization

pca = PCA(n_components=3)
embeddings_3d = pca.fit_transform(embeddings_100d)

# Create 3D scatter plot
fig_wv100 = go.Figure(data=[go.Scatter3d(
    x=embeddings_3d[:, 0],
    y=embeddings_3d[:, 1],
    z=embeddings_3d[:, 2],
    mode='markers+text',
    text=words_to_plot,
    textposition='top center',
    marker=dict(
        size=8,
        color='blue',
        opacity=0.8
    )
)])

fig_wv100.update_layout(
    title="3D Projection of GloVe-100 Word Embeddings",
    scene=dict(
        xaxis_title='PC 1',
        yaxis_title='PC 2',
        zaxis_title='PC 3',
        xaxis=dict(nticks=10, range=[-4, 4]),
        yaxis=dict(nticks=10, range=[-4, 4]),
        zaxis=dict(nticks=10, range=[-4, 4]),
    )
)

fig_wv100.show()

In [ ]:
wv100["uncle"] - wv100["man"] + wv100["woman"]

array([ 6.38110042e-01, -7.76199698e-02,  3.38160008e-01,  3.02094012e-01,
        1.48825794e-01,  1.00976992e+00, -5.54409981e-01, -7.13069737e-02,
        1.11689985e-01, -2.94230014e-01, -4.39969987e-01,  2.07439989e-01,
        4.04479980e-01,  4.98520017e-01,  1.99169993e-01, -5.49869061e-01,
        3.64199877e-02, -1.46899998e-01, -4.48220015e-01,  7.72170007e-01,
       -7.84291029e-01,  6.43920004e-02,  4.27118987e-01,  5.29929996e-01,
        1.16329998e-01, -7.05060363e-02, -9.24950063e-01, -1.87159991e+00,
        6.27029955e-01,  5.08570015e-01,  3.32423985e-01,  6.91089988e-01,
        1.52393401e+00, -3.51750016e-01, -6.35850012e-01,  3.99290025e-01,
        1.35438025e-01, -1.39069974e-01,  8.87390018e-01, -2.89150178e-02,
       -7.55699873e-02,  5.50137043e-01,  7.64997303e-03, -7.18330026e-01,
        2.68040001e-01, -6.52755946e-02, -8.79854977e-01,  2.45618001e-01,
        4.44469988e-01, -3.63889992e-01, -5.27029991e-01,  2.19989985e-01,
        9.34850037e-01,  

In [ ]:
wv100["aunt"]

array([ 0.20861  , -0.16902  ,  0.33447  ,  0.043482 , -0.27338  ,
        0.53489  , -0.34282  ,  0.10549  ,  0.29764  , -0.0047136,
       -0.039522 ,  0.17831  , -0.12561  ,  0.46411  ,  0.048369 ,
       -0.082772 ,  0.10357  , -0.052958 , -0.21689  ,  1.1943   ,
       -0.18743  ,  0.69135  ,  0.29401  ,  0.45871  ,  0.41993  ,
        0.33171  , -1.0771   , -1.419    , -0.20005  ,  0.63959  ,
        0.30314  ,  0.51684  ,  1.4939   ,  0.097429 , -0.64012  ,
        0.67043  ,  0.27266  ,  0.14156  ,  0.87618  , -0.0049375,
       -0.066969 ,  0.22421  ,  0.029059 , -0.50297  ,  0.12929  ,
        0.31207  , -0.95988  ,  0.098352 ,  0.72619  , -0.34323  ,
       -0.10229  ,  0.38255  ,  1.5315   ,  0.38464  , -0.18369  ,
       -0.7087   , -0.60978  ,  0.10066  , -0.81362  ,  0.21249  ,
        0.25147  ,  0.96788  ,  0.2786   , -0.28582  ,  0.30714  ,
        0.022422 , -0.20459  ,  0.096513 ,  0.17629  , -0.29374  ,
       -0.40988  , -0.17367  , -0.064264 , -0.31721  ,  0.3849

In [ ]:
# Analogy: uncle - man + woman
analogy_results100 = wv100.most_similar(positive=['uncle', 'woman'], negative=['man'], topn=10)
print(analogy_results100)


[('aunt', 0.8368030190467834), ('daughter', 0.8227197527885437), ('niece', 0.8220989108085632), ('grandmother', 0.8220454454421997), ('mother', 0.8078984022140503), ('wife', 0.7898010015487671), ('cousin', 0.7828284502029419), ('granddaughter', 0.7685597538948059), ('father', 0.7636010050773621), ('husband', 0.7516083717346191)]


In [ ]:
# Analogy: uncle - man + woman
analogy_results100 = wv100.most_similar(positive=['uncle', 'woman'], negative=['man'], topn=10)
print(analogy_results100)

[('aunt', 0.8368030190467834), ('daughter', 0.8227197527885437), ('niece', 0.8220989108085632), ('grandmother', 0.8220454454421997), ('mother', 0.8078984022140503), ('wife', 0.7898010015487671), ('cousin', 0.7828284502029419), ('granddaughter', 0.7685597538948059), ('father', 0.7636010050773621), ('husband', 0.7516083717346191)]


## Why vector representations?

## Outline of the Course