In [ ]:
import torch

x = torch.tensor([1, 3, 5])
y = torch.tensor([3, 7, 4])

x + y

tensor([ 4, 10,  9])

In [ ]:
# Dot product

torch.dot(x, y)

tensor(44)

In [ ]:
x @ y

tensor(44)

In [ ]:
x * y

tensor([ 3, 21, 20])

In [ ]:
dZ = torch.tensor([
    [
        [1, 0, 0],
        [2, 0, 0],
    ],
    [
        [0, 1, 0],
        [0, 2, 0],
    ],
    [
        [0, 0, 1],
        [0, 0, 2]
    ]
])

dZ

tensor([[[1, 0, 0],
         [2, 0, 0]],

        [[0, 1, 0],
         [0, 2, 0]],

        [[0, 0, 1],
         [0, 0, 2]]])

In [ ]:
dZ.mT

tensor([[[1, 2],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [1, 2],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [1, 2]]])

In [ ]:
dZ.mT

torch.Size([3, 3, 2])

In [ ]:
S = torch.tensor([
    [1, 2, 3],
    [3, 5, 6],
    [7, 8, 9]
])

S.shape

torch.Size([3, 3])

In [ ]:
dZ.mT @ S

RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [3, 2] but got: [3, 3].